all:ball_movement_tests.o runall.o unity.o unity_fixture.o

ball_movement_tests.o:
	gcc -c ball_movement_tests.c -o ../../build/ball_movement_tests.o

runall.o:
	gcc -c runall.c -o ../../build/runall.o

unity.o:
	gcc -c ../../unity/unity.c -o ../../build/unity.o

unity_fixture.o:
	gcc -c ../../unity/unity_fixture.c -o ../../build/unity_fixture.o
